unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: true
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_personal_form: false
  contact_message_sitewide_form: true
  node_advertisement_form: false
  node_article_form: false
  node_associate_member_form: false
  node_column_form: false
  node_community_updates_form: false
  node_fillable_forms_form: false
  node_job_listings_form: false
  node_landing_page_form: false
  node_marquee_promotion_form: false
  node_page_form: false
  node_panel_form: false
  node_product_form: false
  node_real_estate_listing_form: false
  node_webform_form: true
  comment_comment_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
