registration_terms_style: 0
registration_container: 1
login_terms_style: 3
login_container: 1
user_profile_display: true
accept_every_login: false
except_roles:
  administrator: administrator
  page_creator: 0
  layout_manager: 0
  page_reviewer: 0
  landing_page_creator: 0
  landing_page_reviewer: 0
  media_creator: 0
  media_manager: 0
  article_creator: 0
  article_reviewer: 0
  associate_member_creator: 0
  associate_member_reviewer: 0
  column_creator: 0
  column_reviewer: 0
  community_updates_creator: 0
  community_updates_reviewer: 0
  fillable_forms_creator: 0
  fillable_forms_reviewer: 0
  job_listings_creator: 0
  job_listings_reviewer: 0
  marquee_promotion_creator: 0
  marquee_promotion_reviewer: 0
  panel_creator: 0
  panel_reviewer: 0
  product_creator: 0
  product_reviewer: 0
  real_estate_listing_creator: 0
  real_estate_listing_reviewer: 0
  webform_creator: 0
  webform_reviewer: 0
registration_modal_terms: true
login_modal_terms: true
_core:
  default_config_hash: denrqScJlMiBdsks_UljTePRT-AAq-8PPlSluUFaxUs
