<?php

/**
 * @file
 * Code for the Commerce Webform Order module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Implements hook_theme().
 */
function commerce_webform_order_theme() {
  return [
    'webform_handler_commerce_webform_order_summary' => [
      'variables' => ['settings' => NULL, 'handler' => []],
    ],
  ];
}

/**
 * Implements hook_entity_base_field_info().
 */
function commerce_webform_order_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = commerce_webform_order_get_base_fields();

  // Add module base fields to add relation between webform submissions, orders
  // and order items.
  if ($entity_type->id() == 'commerce_order_item') {
    return ['commerce_webform_order_submissions' => $fields['commerce_webform_order_submissions']];
  }
  elseif ($entity_type->id() == 'webform_submission') {
    return ['commerce_webform_order_orders' => $fields['commerce_webform_order_orders']];
  }
}

/**
 * Returns the base fields to add the needed relations.
 *
 * @return array
 *   The module base fields.
 */
function commerce_webform_order_get_base_fields() {
  $fields = [];

  $fields['commerce_webform_order_submissions'] = BaseFieldDefinition::create('entity_reference')
    ->setLabel(t('Webform submission'))
    ->setDescription(t('The webform submission which has created by this order item.'))
    ->setCardinality(1)
    ->setRequired(FALSE)
    ->setSetting('target_type', 'webform_submission')
    ->setSetting('handler', 'default')
    ->setTranslatable(FALSE)
    ->setDisplayConfigurable('form', FALSE)
    ->setDisplayOptions('form', [
      'region' => 'hidden',
      'weight' => 0,
    ])
    ->setDisplayConfigurable('view', TRUE)
    ->setDisplayOptions('view', [
      'region' => 'hidden',
      'weight' => 0,
    ]);

  $fields['commerce_webform_order_orders'] = BaseFieldDefinition::create('entity_reference')
    ->setLabel(t('Commerce orders'))
    ->setDescription(t('The commerce orders which have been created by this webform submission.'))
    // One order could be created by multiple submissions.
    ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
    ->setRequired(FALSE)
    ->setSetting('target_type', 'commerce_order')
    ->setSetting('handler', 'default')
    ->setTranslatable(FALSE)
    ->setDisplayConfigurable('form', FALSE)
    ->setDisplayOptions('form', [
      'region' => 'hidden',
      'weight' => 0,
    ])
    ->setDisplayConfigurable('view', TRUE)
    ->setDisplayOptions('view', [
      'region' => 'hidden',
      'weight' => 0,
    ]);

  return $fields;
}
